<a href="https://colab.research.google.com/github/Arvin-007Elite/ML-Projects/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

##Comparing Lists vs NP_Arrays

In [8]:
# Lists
List1 = [1,2,3,4,5]
print(List1)
type(List1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

#Numpy arrays r faster than Lists
Normally lists produces CSV answers
but
Numpy gives whole number values as answers
Even in float !

In [11]:
# 1-Dimension
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

2 - Dimensions , which displays , rows and columns as values

In [6]:
b = np.array([(1,2,3,4,5), (6,7,8,9,10)])
print(b)
b.shape
# with tuples
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])
c
# with lists

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Converting np_array as float vallue

In [12]:
b = np.array([(1,2,3,4,5), (6,7,8,9,10)],dtype=float)
print(b)
b.shape

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


(2, 5)

In [15]:
# create  a array of zeros
x = np.zeros((3,4))
print(x)
# create  a array of ones
y = np.ones((3,4))
print(y)
# create a full array  with a particular value
z = np.full((4,5),5)
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [16]:
# Identity Matrix , which has 0 and 1 diagnolly and same rows and cols
a = np.eye(4) # 4 rows and 4 columns
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# numpy array with random values
a = np.random.random((3,4))
print(a)
# now only with int


[[0.88697632 0.49858933 0.27822846 0.89197641]
 [0.00301691 0.45914635 0.10693788 0.4158475 ]
 [0.14733123 0.75553713 0.11851819 0.60399125]]


In [18]:
# random integer with specific range
c = np.random.randint(10,100,(3,4))
print(c)
# 1o to 100 is range

[[68 27 67 22]
 [17 30 70 86]
 [50 13 77 97]]


In [28]:
# array of evenly spaced (sequence format and gap)
d = np.linspace(10,30,4)
print(d)
# 10 and 30 r start and end value , 5 is no of values
# we can also use another method , but differnece mentioned
e = np.arange(10,30,9)
print(e)
# here 5 is sequence order
# e.shape
#reshapeing a matrix wth shape method itslef!
e.shape = (1,3)
e.shape


[10.         16.66666667 23.33333333 30.        ]
[10 19 28]


(1, 3)

In [29]:
# convert a list to np_array
list1 = [1,2,3,4,5]

np_array = np.asarray(list1)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [30]:
# Analysing numpy array
c = np.random.randint(10,100,(3,4))
print(c)
# to find rows and columns
c.shape


[[11 79 49 53]
 [24 30 20 53]
 [56 72 97 30]]


(3, 4)

In [31]:
# to find dimension (2d , 1d , or 3d )
print(c.ndim)
# number of elements in an array ( 3 * 4 total )
print(c.size)

2
12


In [32]:
# checking the data type in array
print(c.dtype)

int64


In [33]:
# maths operations on np_array
# adding lists

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
total = list1 + list2
print(total)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [34]:
# but we want to add values , so use in np!

c = np.random.randint(10,20,(3,4))

d = np.random.randint(30,40,(3,4))

print(c,d)
print(c + d)
print(c - d)
print(c * d)
print(c / d)

[[11 18 15 16]
 [10 18 14 15]
 [14 13 10 17]] [[39 39 33 30]
 [30 34 34 30]
 [34 38 37 36]]
[[50 57 48 46]
 [40 52 48 45]
 [48 51 47 53]]
[[-28 -21 -18 -14]
 [-20 -16 -20 -15]
 [-20 -25 -27 -19]]
[[429 702 495 480]
 [300 612 476 450]
 [476 494 370 612]]
[[0.28205128 0.46153846 0.45454545 0.53333333]
 [0.33333333 0.52941176 0.41176471 0.5       ]
 [0.41176471 0.34210526 0.27027027 0.47222222]]


In [68]:
# alternate method for  above method

print(np.add(c,d))

print(np.subtract(c,d))

print(np.multiply(c,d))
print(np.divide(c,d))

[[56 55 51 47]
 [45 53 44 40]
 [48 51 55 51]]
[[-22 -23 -15 -13]
 [-15 -15 -24 -20]
 [-20 -25 -19 -21]]
[[663 624 594 510]
 [450 646 340 300]
 [476 494 666 540]]
[[0.43589744 0.41025641 0.54545455 0.56666667]
 [0.5        0.55882353 0.29411765 0.33333333]
 [0.41176471 0.34210526 0.48648649 0.41666667]]


In [36]:
# array manipulation

c = np.random.randint(10,20,(3,4))
print(c.shape)

(3, 4)


In [37]:
# Transpaose  converts (3,4 matrix as ulta)
f = np.transpose(c)
print(f)
print(f.shape)

[[17 15 14]
 [16 19 13]
 [18 10 18]
 [17 10 15]]
(4, 3)


In [38]:

# transposing with another method
trans = c.T
print(trans.shape)


(4, 3)


In [39]:
# to reshape the array
rshape = c.reshape(4,3)
print(c.shape)

(3, 4)


In [57]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
np.vstack((n1,n2))


array([[10, 20, 30],
       [40, 50, 60]])

In [58]:
np.vstack((n2,n1))

array([[40, 50, 60],
       [10, 20, 30]])

In [59]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [60]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [62]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

In [67]:
np.intersect1d(n1,n2)
# common elements

array([50, 60])

In [66]:
np.setdiff1d(n1,n2)
#unique values of 1st set

array([10, 20, 30, 40])

In [71]:
# np array arithmetics
n1 = np.array([10,20])
n2 = np.array([30,40])
np.sum([n1,n2])
# 10+20+40+30

100

In [72]:
n1 = np.array([10,20])
n2 = np.array([30,40])
np.sum([n1,n2] , axis =0)
# 10 + 30 , 20+ 40

array([40, 60])

In [74]:
n1 = np.array([10,20])
n2 = np.array([30,40])
np.sum([n1,n2], axis=1)
# 10 + 20 , 30 + 40

array([30, 70])

In [76]:
n3 = n1 + 1
n3
# add 1 with every element
# same for - , * , /

array([11, 21])

In [77]:
np.mean(n1)

15.0

In [78]:
np.median(n1)

15.0

In [79]:
np.std(n1)

5.0

In [85]:
n1 = np.array([(10,20,30) , (40,50,60), (70,80,90)])
n1
n1[0]
# row wise


array([[10, 20, 30]])

In [87]:
n1[:,1]
# col wise

array([20, 50, 80])

In [88]:
# matrix multilication
n1 = np.array([(10,20,30) , (40,50,60), (70,80,90)])
n2 = np.array([(10,20,30) , (40,50,60), (70,80,90)])
n1.dot(n2)

array([[ 3000,  3600,  4200],
       [ 6600,  8100,  9600],
       [10200, 12600, 15000]])

In [89]:
n1 = np.array([10,20,30,40,50,60])
np.save('sv_arr' , n1)

In [91]:
n2 = np.load('sv_arr.npy')
n2

array([10, 20, 30, 40, 50, 60])