<a href="https://colab.research.google.com/github/Arvin-007Elite/PYTHON/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

##Comparing Lists vs NP_Arrays

In [ ]:
# Lists
List1 = [1,2,3,4,5]
print(List1)
type(List1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

#Numpy arrays r faster than Lists
Normally lists produces CSV answers
but
Numpy gives whole number values as answers
Even in float !

In [ ]:
# 1-Dimension
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

2 - Dimensions , which displays , rows and columns as values

In [ ]:
b = np.array([(1,2,3,4,5), (6,7,8,9,10)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

Converting np_array as float vallue

In [ ]:
b = np.array([(1,2,3,4,5), (6,7,8,9,10)],dtype=float)
print(b)
b.shape

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


(2, 5)

In [ ]:
# create  a array of zeros
x = np.zeros((3,4))
print(x)
# create  a array of ones
y = np.ones((3,4))
print(y)
# create a full array  with a particular value
z = np.full((4,5),5)
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
# Identity Matrix , which has 0 and 1 diagnolly and same rows and cols
a = np.eye(4) # 4 rows and 4 columns
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# numpy array with random values
a = np.random.random((3,4))
print(a)
# now only with int
b = np.random.randint((10,100))

[[0.33958053 0.12202047 0.19105168 0.62294133]
 [0.04449002 0.61613621 0.43449398 0.82087354]
 [0.28921241 0.10733003 0.83787861 0.02431845]]


In [ ]:
# random integer with specific range
c = np.random.randint(10,100,(3,4))
print(c)
# 1o to 100 is range

[[22 92 16 70]
 [80 73 24 71]
 [74 75 56 63]]


In [ ]:
# array of evenly spaced (sequence format and gap)
d = np.linspace(10,30,5)
print(d)
# 10 and 30 r start and end value , 5 is no of values
# we can also use another method , but differnece mentioned
e = np.arange(10,30,5)
print(e)
# here 5 is sequence order

[10. 15. 20. 25. 30.]
[10 15 20 25]


In [ ]:
# convert a list to np_array
list1 = [1,2,3,4,5]

np_array = np.asarray(list1)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# Analysing numpy array
c = np.random.randint(10,100,(3,4))
print(c)
# to find rows and columns
c.shape


[[70 79 52 79]
 [47 85 56 11]
 [48 10 20 86]]


(3, 4)

In [ ]:
# to find dimension (2d , 1d , or 3d )
print(c.ndim)
# number of elements in an array ( 3 * 4 total )
print(c.size)

2
12


In [ ]:
# checking the data type in array
print(c.dtype)

int64


In [ ]:
# maths operations on np_array
# adding lists

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
total = list1 + list2
print(total)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# but we want to add values , so use in np!

c = np.random.randint(10,20,(3,4))

d = np.random.randint(30,40,(3,4))

print(c,d)
print(c + d)
print(c - d)
print(c * d)
print(c / d)

[[13 17 15 13]
 [14 13 18 19]
 [12 17 10 10]] [[30 34 34 31]
 [39 31 34 33]
 [35 32 37 38]]
[[43 51 49 44]
 [53 44 52 52]
 [47 49 47 48]]
[[-17 -17 -19 -18]
 [-25 -18 -16 -14]
 [-23 -15 -27 -28]]
[[390 578 510 403]
 [546 403 612 627]
 [420 544 370 380]]
[[0.43333333 0.5        0.44117647 0.41935484]
 [0.35897436 0.41935484 0.52941176 0.57575758]
 [0.34285714 0.53125    0.27027027 0.26315789]]


In [ ]:
# alternate method for  above method

print(np.add(c,d))
print(np.subtract(c,d))

print(np.multiply(c,d))
print(np.divide(c,d))

[[43 51 49 44]
 [53 44 52 52]
 [47 49 47 48]]
[[-17 -17 -19 -18]
 [-25 -18 -16 -14]
 [-23 -15 -27 -28]]
[[390 578 510 403]
 [546 403 612 627]
 [420 544 370 380]]
[[0.43333333 0.5        0.44117647 0.41935484]
 [0.35897436 0.41935484 0.52941176 0.57575758]
 [0.34285714 0.53125    0.27027027 0.26315789]]


In [ ]:
# array manipulation

c = np.random.randint(10,20,(3,4))
print(c.shape)

(3, 4)


In [ ]:
# Transpaose  converts (3,4 matrix as ulta)
f = np.transpose(c)
print(f)
print(f.shape)

[[12 15 17]
 [17 15 14]
 [19 12 18]
 [19 19 10]]
(4, 3)


In [ ]:
# transposing with another method
trans = c.T
print(trans.shape)


(4, 3)


In [ ]:
# to reshape the array
rshape = c.reshape(4,3)
print(c.shape)

(3, 4)
