<a href="https://colab.research.google.com/github/Arvin-007Elite/PYTHON/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##Comparing Lists vs NP_Arrays

In [3]:
# Lists
List1 = [1,2,3,4,5]
print(List1)
type(List1)

[1, 2, 3, 4, 5]


list

In [4]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

#Numpy arrays r faster than Lists
Normally lists produces CSV answers
but
Numpy gives whole number values as answers
Even in float !

In [5]:
# 1-Dimension
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

2 - Dimensions , which displays , rows and columns as values

In [6]:
b = np.array([(1,2,3,4,5), (6,7,8,9,10)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

Converting np_array as float vallue

In [7]:
b = np.array([(1,2,3,4,5), (6,7,8,9,10)],dtype=float)
print(b)
b.shape

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


(2, 5)

In [8]:
# create  a array of zeros
x = np.zeros((3,4))
print(x)
# create  a array of ones
y = np.ones((3,4))
print(y)
# create a full array  with a particular value
z = np.full((4,5),5)
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [9]:
# Identity Matrix , which has 0 and 1 diagnolly and same rows and cols
a = np.eye(4) # 4 rows and 4 columns
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# numpy array with random values
a = np.random.random((3,4))
print(a)
# now only with int


[[0.66547278 0.03593775 0.55663071 0.99249003]
 [0.77700414 0.0760882  0.36461132 0.22814077]
 [0.08716037 0.62318642 0.41843207 0.46980696]]


In [13]:
# random integer with specific range
c = np.random.randint(10,100,(3,4))
print(c)
# 1o to 100 is range

[[81 26 74 39]
 [27 34 76 78]
 [15 81 29 15]]


In [16]:
# array of evenly spaced (sequence format and gap)
d = np.linspace(10,30,4)
print(d)
# 10 and 30 r start and end value , 5 is no of values
# we can also use another method , but differnece mentioned
e = np.arange(10,30,9)
print(e)
# here 5 is sequence order

[10.         16.66666667 23.33333333 30.        ]
[10 19 28]


In [18]:
# convert a list to np_array
list1 = [1,2,3,4,5]

np_array = np.asarray(list1)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [19]:
# Analysing numpy array
c = np.random.randint(10,100,(3,4))
print(c)
# to find rows and columns
c.shape


[[40 84 40 49]
 [94 76 53 60]
 [13 67 57 87]]


(3, 4)

In [20]:
# to find dimension (2d , 1d , or 3d )
print(c.ndim)
# number of elements in an array ( 3 * 4 total )
print(c.size)

2
12


In [21]:
# checking the data type in array
print(c.dtype)

int64


In [22]:
# maths operations on np_array
# adding lists

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
total = list1 + list2
print(total)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [23]:
# but we want to add values , so use in np!

c = np.random.randint(10,20,(3,4))

d = np.random.randint(30,40,(3,4))

print(c,d)
print(c + d)
print(c - d)
print(c * d)
print(c / d)

[[14 11 15 10]
 [14 12 15 17]
 [10 18 14 16]] [[39 39 30 37]
 [33 32 33 33]
 [31 39 38 32]]
[[53 50 45 47]
 [47 44 48 50]
 [41 57 52 48]]
[[-25 -28 -15 -27]
 [-19 -20 -18 -16]
 [-21 -21 -24 -16]]
[[546 429 450 370]
 [462 384 495 561]
 [310 702 532 512]]
[[0.35897436 0.28205128 0.5        0.27027027]
 [0.42424242 0.375      0.45454545 0.51515152]
 [0.32258065 0.46153846 0.36842105 0.5       ]]


In [24]:
# alternate method for  above method

print(np.add(c,d))
print(np.subtract(c,d))

print(np.multiply(c,d))
print(np.divide(c,d))

[[53 50 45 47]
 [47 44 48 50]
 [41 57 52 48]]
[[-25 -28 -15 -27]
 [-19 -20 -18 -16]
 [-21 -21 -24 -16]]
[[546 429 450 370]
 [462 384 495 561]
 [310 702 532 512]]
[[0.35897436 0.28205128 0.5        0.27027027]
 [0.42424242 0.375      0.45454545 0.51515152]
 [0.32258065 0.46153846 0.36842105 0.5       ]]


In [25]:
# array manipulation

c = np.random.randint(10,20,(3,4))
print(c.shape)

(3, 4)


In [27]:
# Transpaose  converts (3,4 matrix as ulta)
f = np.transpose(c)
print(f)
print(f.shape)

[[16 16 19]
 [12 14 13]
 [18 10 10]
 [15 15 18]]
(4, 3)


In [ ]:
# transposing with another method
trans = c.T
print(trans.shape)


(4, 3)


In [ ]:
# to reshape the array
rshape = c.reshape(4,3)
print(c.shape)

(3, 4)
