<a href="https://colab.research.google.com/github/Arvin-007Elite/ML-Projects/blob/master/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

np_arr1 = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
np_arr2 = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
np_arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
print(type(np_arr2))

<class 'numpy.ndarray'>


In [6]:
list1 = [11,12,13,14,15]
list2 = [16,17,18,19,20]
list1

[11, 12, 13, 14, 15]

In [7]:
print(type(list1))

<class 'list'>


In [16]:
np_arr3 = np.array([(1,2,3,4,5) , (6,7,8,9,10)], dtype=float)
np_arr4 = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
np_arr3 + np_arr4
# list of np + tuple of np can be done

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.]])

In [17]:
np_arr5 = np.asarray(list1)
np_arr5

array([11, 12, 13, 14, 15])

In [18]:
np_arr6 = np.zeros((2,3))
np_arr6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np_arr7 = np.ones((2,3))
np_arr7

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np_arr8 = np.full((2,3),4)
np_arr8

array([[4, 4, 4],
       [4, 4, 4]])

In [21]:
np_arr6 = np.eye(2)
np_arr6

array([[1., 0.],
       [0., 1.]])

In [23]:
np_rand = np.random.rand(2,3)
np_randint = np.random.randint(10,100,(2,3))
np_rand + np_randint

array([[65.62764811, 88.5254011 , 60.06949877],
       [53.67665515, 77.0872309 , 45.34574106]])

In [24]:
print(np_arr3  , np_arr3 + 1)


[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]] [[ 2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11.]]


In [25]:
print(np_arr5.ndim)

1


In [26]:
np_arr4.shape

(2, 5)

In [27]:
print(np_arr3.size)

10


In [29]:
np_arr4.shape = (5,2)
np_arr4.shape

(5, 2)

In [30]:
np_arr4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [37]:

np_arr3 = np_arr3.reshape(5,2)
np_arr3

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [38]:
np_arr10 = np.linspace(10,100,4)
np_arr10

array([ 10.,  40.,  70., 100.])

In [39]:
np_arr11 = np.arange(10,100,4)
np_arr11

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
       78, 82, 86, 90, 94, 98])

In [42]:
np_arr3 = np_arr3.transpose()
np_arr3

array([[ 1.,  3.,  5.,  7.,  9.],
       [ 2.,  4.,  6.,  8., 10.]])

In [43]:
np_arr3 = np_arr3.T
np_arr3

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [46]:
np.vstack((np_arr1,np_arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
np.hstack((np_arr1,np_arr2))

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

In [48]:
np.column_stack((np_arr1,np_arr2))

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

In [50]:
print(np_arr1 + np_arr2)

np.add(np_arr1,np_arr2)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [54]:
np.sum([np_arr1,np_arr2])


110

In [55]:
np.sum([np_arr1,np_arr2] , axis = 0)


array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [56]:
np.sum([np_arr1,np_arr2] , axis = 1)

array([[ 7,  9, 11, 13, 15],
       [ 7,  9, 11, 13, 15]])

In [57]:
np_arr11 = np.array([10,20,30,40,50,60])
np_arr12 = np.array([20,30,60,70,80,90,100])
np.intersect1d(np_arr11,np_arr12)

array([20, 30, 60])

In [58]:
np_arr11 = np.array([10,20,30,40,50,60])
np_arr12 = np.array([20,30,60,70,80,90,100])
np.setdiff1d(np_arr11,np_arr12)

array([10, 40, 50])

In [59]:
np.mean(np_arr11)

35.0

In [60]:
np.median(np_arr11)

35.0

In [62]:
np.std(np_arr11)

17.07825127659933

In [64]:
np_arr11[4:7]

array([50, 60])

In [69]:
np_arr1[:,1]

array([2, 7])

In [74]:
np_arr14 = np.array([(1,2,3,4,5), (6,7,8,9,10)])
np_arr15 = np.array([(1,2,3,4,5), (6,7,8,9,10)])
np_arr14.dot(np_arr15)
n1 = np.array([(10,20,30) , (40,50,60), (70,80,90)])
n2 = np.array([(10,20,30) , (40,50,60), (70,80,90)])
n1.dot(n2)

array([[ 3000,  3600,  4200],
       [ 6600,  8100,  9600],
       [10200, 12600, 15000]])

In [77]:
n1 = np.save('n1' , n1)

In [84]:
n2 = np.load('n1.npy')


SyntaxError: invalid syntax (<ipython-input-83-0d3dc79357ae>, line 1)